package org.raul.frw;
 
import org.raul.model.Message;
import org.raul.model.PTR;

 
rule "DWM Ptrs"
	when
		PTR (title matches ".*DWM.*");
	then
		insert( Message.info()
		               .title("DWM PTR for Connectors")
		               .details("Handle quickly!")
		               .addTag("DWM")
		               .addTag("Urgent!"));
		                
end


rule "PTRs without attachments are suspect"
	when
		PTR (hasAttachement == false);
	then
		insert( Message.warning()
		               .title("Strange...")
		               .details("No attachment at all")
		               .addTag("Zero attachment folks"));
		               
		insert( Message.info()
		               .title("PTRs without traces should be sent back")
		               .details("Click here to send it back to the logger")
		               .addTag("Zero attachment folks")); 
 
end